---
- name: Automatic Remediation of a webserver
  hosts: all
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 8000
  rules:
    - name: restart web server
      #condition: event.alert.labels.job == "fastapi" and event.alert.status == "firing"
      condition: event.payload.message == "fastapi"
      action:
#        run_job_template:
#          name: Demo Job Template
#          organization: Default
#          job_args:
#            extra_vars:
#               message: from eda
#               sleep: 1

        run_job_template:
          name: EDA Test
          organization: Default
          job_args:
            extra_vars:
               message: from eda
               sleep: 1



...
