---
- name: AlertManager Source Example
  hosts: all
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 8000
        # data_alerts_path: alerts
        # data_host_path: labels.instance
        # data_path_separator: .
#       data_alerts_path: The json path to find alert data. Default to "alerts"
#                         Use empty string "" to treat the whole payload data as
#                         one alert.
#       data_host_path: The json path inside the alert data to find alerting host.
#                       Use empty string "" if there is no need to find host.
#                       Default to  "labels.instance".
#       data_path_separator: The separator to interpret data_host_path and
#                            data_alerts_path. Default to "."
#       skip_original_data: true/false. Default to false
#                           true: put only alert data to the queue
#                           false: put sequentially both the received original
#                                  data and each parsed alert item to the queue.


  rules:
    - name: res
      condition: event.payload.message == "fastapi"
      action:
        run_job_template:
          name: EDA Test
          organization: Default
          job_args:
            extra_vars:
               message: from AlertManager EDA Source
               sleep: 1



...
