---
- name: Poll Datadog for Alerts
  hosts: all
  sources:
    - name: my_custom_poller
      # If local, point to the directory. If in a collection, use fully qualified name.
      source_plugin: extensions/eda/plugins/event_source/datadog_poll.py
      args:
        api_key: "{{ DATADOG_API_KEY }}"
        app_key: "{{ DATADOG_APP_KEY }}"
        delay: 30
        tags: "service:web-server"

  rules:
    - name: Remediate Web Server Alert
      condition: event.monitor_name is match("High CPU on Web Server")
      action:
        run_playbook:
          name: playbooks/restart_web_service.yml


    # EXAMPLE FROM DYNATRACE
    - name: Event payload is defined
      condition: event.payload.eventData['event.category'] == 'AVAILABILITY'
      # condition: event.display_id is defined
      action:
        run_workflow_template:
          name: DYNATRACE Service Restoration
          organization: Default
          job_args:
            extra_vars:
              display_id: "{{ event.payload.eventData['display_id'] }}"
              problem_id: "{{ event.payload.eventData['event.id'] }}"
              _hosts: "{{ event.payload.eventData['host.name'] }}"
              root_cause: "{{ event.payload.eventData['root_cause_entity_name'] | default('') }}"
