---
- name: Listen for events on dt_webhook
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_webhook:
        host: 0.0.0.0
        port: 5000
        token: '{{ dt_webhook_token | default(omit) }}'
      

  rules:
    - name: API Endpoint not available
      condition: event.payload.eventData["event.name"] is match ("Monitoring not available")
      action:
        run_job_template:
          name: "Trigger test playbook"
          organization: "Default"


    - name: Event payload is defined
      condition: event.payload is defined
      action:
        run_job_template:
          name: EDA Test
          organization: Default
          job_args:
            extra_vars:
              host_msg: "{{ event.payload.eventData['host.name'] }}"
              message: From EDA webhook source
              sleep: 1

...
