---
- name: Listen for events on dt_webhook
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_webhook:
        host: 0.0.0.0
        port: 5000
        token: '{{ dt_webhook_token | default(omit) }}'

  rules:

    - name: Get push events on main
      condition: event.payload is defined
      action:
        post_event:
          event:
            display_id: "{{ event.payload.eventData['display_id'] }}"
            _host: "{{ event.payload.eventData['host.name'] }}"


    # - name: API Endpoint not available
    #   condition: event.payload.eventData['event.category'] == 'AVAILABILITY'
    #   action:
    #     debug:
    #       msg: "{{ category }}"

    - name: Event payload is defined
      # condition: event.payload.eventData['event.category'] == 'AVAILABILITY'
      condition: event.display_id is defined
      action:
        run_job_template:
          name: EDA Test
          organization: Default
          job_args:
            extra_vars:
              host_msg: "{{ event._host }}"
              message: From EDA webhook source
              sleep: 1
        # run_playbook:
        #   name: /tmp/demo/test_eda.yml
        #   extra_vars:
        #     display_id: "{{ event.display_id }}"
        #     host_msg: "{{ event._host }}"
        #     message: From EDA webhook source

...
