---
- name: Listen for events on a webhook
  hosts: all

  ## Define our source for events

  sources:
   - instana_webhook:
       host: 0.0.0.0
       port: 6000

  ## Define the conditions we are looking for

  rules:
   - name: Test
     condition: event.payload.message == "Node failed"
     action:
       debug:
