---
- name: Read messages from a kafka topic and act on them
  hosts: kafka.example.com
  ## Define our source for events
  sources:
    - ansible.eda.kafka:
        host: "{{ kafka_host }}"
        port: 9092
        topic: eda-topic
        group_id:

  rules:
    - name: receive event
      condition: event.message != ""

      action:
        run_job_template:
          name: SUBMIT FEEDBACK
          organization: Default
          job_args:
            extra_vars:
               message: from eda
               sleep: 1

...
