---
- name: Read messages from a kafka topic and act on them
  hosts: all
  ## Define our source for events
  sources:
    - ansible.eda.kafka:
        host: "{{ kafka_host }}"
        port: 9092
        topic: eda-topic
        group_id:

  rules:
    - name: receive event
      #condition: event.body != ""
      #condition: event.body == "broke"
      #To check if the pattern exists anywhere in the string. Regex supported
      #condition: event.body is search(pattern,ignorecase=true)
      condition: event.body contains "broke"

      action:
        run_job_template:
          name: EDA Test
          organization: Default
          job_args:
            extra_vars:
               message: From EDA kafka source
               sleep: 1

...
