---
- name: Poll ServiceNow for New Incidents
  hosts: all
  sources:
    - servicenow.itsm.records:
        table: incident
        # A basic query to look for new/active incidents.
        # The plugin will poll based on this query.
        interval: 20 # Polling interval in seconds
        remote_servicenow_timezone: UTC
        sysparm_query: "active=true^state=1"

  rules:
    - name: Match all new incidents
      # The plugin returns the ServiceNow record under the 'record' key.
      # This condition simply ensures a record was returned.
      condition: event.record is defined
      action:
        print_event:
          pretty: true

...
