---
- name: url_check Source Example
  hosts: all
  sources:
    #urls - a list of urls to poll
    #delay - the number of seconds to wait between polling
    #verify_ssl - verify SSL certificate

    - name: check web server
      ansible.eda.url_check:
        urls:
          - "{{ web_server_url }}"
        delay: 10

  rules:
    #- name: Web service check debug
    #  condition: 
    #    any:
    #      - event.url_check.status != "up"
    #      - event.url_check.status_code != 200
    #  action:
    #    debug:

    - name: If the service is down, run a playbook to fix it 
      condition: 
        any:
          - event.url_check.status != "up"
          - event.url_check.status_code != 200
      action:
        run_job_template:
          name: EDA Demo Restart Web Service
          organization: Default
          job_args:
            extra_vars:
               message: From EDA url_check source
               sleep: 1



...
