---
- name: webhook Source Example
  hosts: all
  sources:
    - name: listen for alerts
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        # host:     The hostname to listen to. Set to 0.0.0.0 to listen on all
        #           interfaces. Defaults to 127.0.0.1
        # port:     The TCP port to listen to.  Defaults to 5000
        # token:    The optional authentication token expected from client
        # certfile: The optional path to a certificate file to enable TLS support
        # keyfile:  The optional path to a key file to be used together with certfile
        # password: The optional password to be used when loading the certificate chain
      filters:
        - ansible.eda.json_filter:
            exclude_keys: ['sender','owner']
        - ansible.eda.dashes_to_underscores:

  rules:

    - name: Debug Webhook Event
      condition: 
        any:
          - event.payload is defined
      action:
        debug:

    - name: Get push events on main 
      # condition: event.meta.headers.X_Gitea_Event == "push"
      condition: event.payload is defined
      action:
        post_event:
          event:
            type: "{{ event.meta.headers.X_Gitea_Event }}"
            gitref: "{{ event.payload.ref }}"
            repo_name: "{{ event.payload.repository.name }}"
            author: "{{ event.payload.head_commit.author }}"
            clone_url: "{{ event.payload.repository.clone_url }}"

    - name: Repond to push events
      condition: event.repo_name == "webhook_testing" # and event.type == "push"
      action:
        run_job_template:
          name: EDA Test
          organization: Default
          job_args:
            extra_vars:
               message: From EDA webhook source
               sleep: 1

    - name: Event Payload is defined
      condition: event.payload is defined
      #condition: event.payload.message == "fastapi"
      action:
        run_job_template:
          name: EDA Test
          organization: Default
          job_args:
            extra_vars:
               message: From EDA webhook source
               sleep: 1



...
