---
- name: Restart and validate the web host
  hosts: "{{ _hosts }}"
  gather_facts: false
  become: true

  tasks:
    - name: Restart JBOSS
      ansible.builtin.service:
        name: jws.service
        state: restarted

    - name: Restart Web Service
      ansible.builtin.service:
        name: httpd
        state: restarted

    - name: Pause to let Dynatrace update
      ansible.builtin.pause:
        seconds: 10

    - name: Check Dynatrace problem status
      ansible.builtin.uri:
        url: "https://{{ dynatrace_url }}/api/v2/problems/{{ problem_id }}"
        method: GET
        status_code: 200
        return_content: yes
        headers:
          Authorization: "API-Token {{ dynatrace_api_key }}"
      register: problem_details

    - name: Debug details
      ansible.builtin.debug:
        var: problem_details
        verbosity: 3

    - name: Verify problem is CLOSED
      ansible.builtin.assert:
        that:
          - problem_details.json.status == "CLOSED"
        msg: "Dynatrace problem with ID {{ problem_id }} is still open."
      until: problem_details.json.status == "CLOSED"
      retries: 10
      delay: 20

    - name: Set Follow-On Variables
      ansible.builtin.set_stats:
        data:
          Dynatrace_Issue_state: "{{ problem_details.json.status }}"
          Dynatrace_Issue_ID: "{{ problem_id }}"



...
