---
- name: Restart and validate the web host
  hosts: "{{ _hosts }}"
  gather_facts: false
  become: true
  vars:
    incident_state: 'new'

  tasks:
    - name: Restart JBOSS
      ansible.builtin.service:
        name: jws.service
        state: restarted

    - name: Restart Web Service
      ansible.builtin.service:
        name: httpd
        state: restarted
 
    - name: Check Dynatrace problem status
      ansible.builtin.uri:
        url: "https://{{ dynatrace_url }}/api/v2/problems/{{ problem_id }}"
        method: GET
        status_code: 200
        return_content: yes
        headers:
          Authorization: "API-Token {{ dynatrace_api_key }}"
      register: problem_details
      until: problem_details.json.status == "CLOSED"
      retries: 20
      delay: 20

    - name: Debug details
      ansible.builtin.debug:
        var: problem_details
        verbosity: 3

    - name: Verify problem is CLOSED
      ansible.builtin.assert:
        that:
          - problem_details.json.status == "CLOSED"
        msg: "Dynatrace problem with ID {{ problem_id }} is still open."
      ignore_errors: true

    - name: Update incident_state
      when: problem_details.json.status == "CLOSED"
      ansible.builtin.set_fact:
        incident_state: "closed"

    - name: Set Follow-On Variables
      ansible.builtin.set_stats:
        data:
          Dynatrace_Issue_state: "{{ problem_details.json.status }}"
          Dynatrace_Issue_ID: "{{ problem_id }}"
          incident_state: "{{ incident_state }}"



...
