---
- name: Restart and validate the web host
  hosts: "{{ _hosts }}"
  gather_facts: false
  become: true

  tasks:
    - name: Restart JBOSS
      ansible.builtin.service:
        name: jws.service
        state: restarted

    - name: Restart Web Service
      ansible.builtin.service:
        name: httpd
        state: restarted
 
    - name: Check for Problem Status in Dynatrace
      ansible.builtin.include_tasks:
        file: dynatrace_validate_closed.yml
      until: problem_details.json.status == "CLOSED"
      retries: 20
      delay: 20

    - name: Verify problem is CLOSED
      ansible.builtin.assert:
        that:
          - problem_details.json.status == "CLOSED"
        msg: "Dynatrace problem with ID {{ problem_id }} is still open."

    - name: Set Follow-On Variables
      ansible.builtin.set_stats:
        data:
          Dynatrace_Issue_state: "{{ problem_details.json.status }}"
          Dynatrace_Issue_ID: "{{ problem_id }}"



...
