---
- name: Stop JBOSS service
  hosts: "{{ _hosts }}"
  gather_facts: false
  become: true

  tasks:
    # - name: Stop JBOSS service
    #   ansible.builtin.service:
    #     name: jws.service
    #     state: stopped
    #     enabled: true

    # - name: Stop httpd service
    #   ansible.builtin.service:
    #     name: httpd.service
    #     state: stopped
    #     enabled: true

    - name: Kill service
      ansible.builtin.command: killall -9 java

    - name: Get service status
      ansible.builtin.command: systemctl status jws

    - name: Kill service
      ansible.builtin.command: killall -9 httpd

    - name: Get service status
      ansible.builtin.command: systemctl status httpd