---
- name: Test EDA
  hosts: "{{ _hosts | default('localhost') }}"
  become: false
  gather_facts: false
  tasks:

  - name: Debug EDA Event Data
    ansible.builtin.debug:
      msg: "{{ message }}"